### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by dmysona92** [skandlab/PUREE#12]
When submitting to https://puree.genome.sg/ I get Error: Request failed with status code 504

Also when running the API get the error:  raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

My file is over 100MB. Is there an issue with the server backend? Thanks!!

**Comment by tanmay2893** [comment]
Hi. Can you let us know the exact file size you are trying to upload?

**Comment by dmysona92** [comment]
It is 201 megabytes

David

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tanmay2893** [comment]
We have increased the file size limit. Could you please try it again and let us know if it works.
Thanks!

**Comment by dmysona92** [comment]
I tried again and got the following error message:

C:\Users\dmysona\Box\EndometrialCA_Immunology\Research\GammaDelta_TCGA\scripts\run_puree.py
Sample names were not encrypted... Encryption is completed.
Traceback (most recent call last):
  File
"C:\Users\dmysona\Mamba\envs\PURE\lib\site-packages\requests\models.py",
line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\dmysona\Mamba\envs\PURE\lib\json\__init__.py", line 346,
in loads
    return _default_decoder.decode(s)
  File "C:\Users\dmysona\Mamba\envs\PURE\lib\json\decoder.py", line 337, in
decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\dmysona\Mamba\envs\PURE\lib\json\decoder.py", line 355, in
raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File
"C:\Users\dmysona\Box\EndometrialCA_Immunology\Research\GammaDelta_TCGA\scripts\run_puree.py",
line 13, in <module>
    purities_and_logs = p.get_output(test_data_path, gene_id_nomenclature)
  File
"C:\Users\dmysona\Mamba\envs\PURE\lib\site-packages\puree\puree_api.py",
line 194, in get_output
    id = file_output[0].json()['id']
  File
"C:\Users\dmysona\Mamba\envs\PURE\lib\site-packages\requests\models.py",
line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char
0)

**Comment by tanmay2893** [comment]
Can you check if you are providing any index column as well. The file should not contain any index column. It should either be the sample ID or the gene ID. There should not be any row id in addition to either of the above columns. It seems like the model is getting additional columns. We have tested the website for 1000 samples containing ~20k genes and it seems to be working fine.

**Comment by dmysona92** [comment]
thank you for the help! It was bc there was not a column name for the first
column. Your algorithm worked!

David
