### ISSUE TITLE
High purity in normal samples

### ISSUE THREAD

**Issue by WuRAFY** [skandlab/PUREE#5]
Hi, thanks for the tool. I recently tried PUREE on a LUAD dataset (Chen et.al, 2020) which was also demostrated in the article. I run PUREE on the website using FPKM matrix with ensembl ids. 
```
           ENSG00000000003 ENSG00000000005 ENSG00000000419 ENSG00000000457
A006_RNA_N           12.12            0.10           66.18            5.42
A006_RNA_T           15.54            0.04           64.84            6.47
A008_RNA_N            6.91            0.00           42.03            3.74
A015_RNA_T           21.12            0.00           27.48            3.13
A021_RNA_N            4.43            0.00           23.39            1.61
```
But I found that the purity of normal samples estimated by PUREE was higher than expected. It's really confusing. Could you help?

![Rplot02](https://github.com/skandlab/PUREE/assets/64182733/c5ad8b72-6b5a-4c02-8cdd-76bfc98f2056)

**Comment by erevkov** [comment]
Hi, thank you for trying PUREE! 

The input data format looks correct and the tumor samples' purity estimates look reasonable. However, in short, we do not recommend running PUREE on healthy tissue samples. PUREE was developed to estimate tumor purity in solid tumor samples, which is essentially the joint process of estimating proportions of cancer cells (p) and tumor stroma (1-p) in the tumor sample. This task is different from classifying between tumor and healthy tissue samples. If you apply PUREE to healthy tissue samples (or adjacent normal samples), it is not clear what the expected result should be. For example, healthy epithelial tissue samples may have a distinct stromal/immune composition as well as healthy epithelial cell populations that are underrepresented in tumors.
