### ISSUE TITLE
Requests for code modules

### ISSUE THREAD

**Issue by liwangchang** [skandlab/PUREE#6]
Dear developer, can you provide the original code of the program?

**Comment by erevkov** [comment]
Hi, thank you for your interest in PUREE! If you wish to obtain the internal source code of the method for academic use, please contact the corresponding author of [the original paper](https://doi.org/10.1038/s42003-023-04764-8).

**Comment by liwangchang** [comment]
Thank you for your reply, I have sent an email to the corresponding author of the original article, but still have not received a reply. Could you put me in touch with the corresponding author of PUREE's article


黎旺长
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "skandlab/PUREE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月24日(星期二) 下午3:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [skandlab/PUREE] Requests for code modules (Issue #6)





 
Hi, thank you for your interest in PUREE! If you wish to obtain the internal source code of the method for academic use, please contact the corresponding author of the original paper.

**Comment by erevkov** [comment]
In this case I would suggest waiting for a reply from the corresponding author. If you do not hear back within a reasonable time frame, perhaps you could try sending a reminder.
