### ISSUE TITLE
Normal tissue generates +-35% tumor

### ISSUE THREAD

**Issue by kjass001** [skandlab/PUREE#9]
Hi,
We tested +-100 RNA exome sample data with interesting output, however, also included are normal lung tissues that get an ouptut of +-35% tumor fraction.
Have you tested this and if yes, did you find similar results?

thanks

**Comment by erevkov** [comment]
Hi, thank you for trying the method!

In short, we do not recommend running PUREE on healthy (or adjacent normal) tissues, as the underlying model was developed exclusively for the estimation of purity in solid tumor samples. For a more extended discussion on this, please see [this comment in an earlier issue](https://github.com/skandlab/PUREE/issues/5#issuecomment-1776673937).

**Comment by kjass001** [comment]
Thanks for your fast reply! Indeed similar findings.
